name: Build and Publish Image (GHCR)

on:
  push:
    branches:
      - master
      - dev-new-ts-changes

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SQL_SERVER_HOST: ${{ secrets.SQL_SERVER_HOST }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}
            ghcr.io/graniterock/grc_intra_company_acct_coding:latest
            ghcr.io/graniterock/grc_intra_company_acct_coding:${{ github.sha }}
          build-args: |
             SQL_SERVER_HOST=${{ secrets.SQL_SERVER_HOST }}
